server:
  port: 8081

spring:
  application:
    name: scrapper
    datasource:
      url: jdbc:postgresql://localhost:5432/scrapper
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      liquibase:
        enabled: false
      jpa:
        hibernate:
          ddl-auto: validate
        open-in-view: false

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
  bot:
    base-url: ${BOT_BASE_URL:http://localhost:8080}
  scheduler:
    interval: 60000
  database:
    access-type: SQL
