server:
  port: 8081

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.type.mapping: linkUpdate:backend.academy.linktracker.scrapper.dto.LinkUpdate

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY:}
    access-token: ${STACKOVERFLOW_ACCESS_KEY:}
  github:
    token: ${GITHUB_TOKEN:}
  bot:
    base-url: ${BOT_BASE_URL:http://localhost:8080}
  scheduler:
    interval: 60000
    batch-size: 100  # 50–500 per NFR
    thread-count: 4  # parallel threads per batch (bonus NFR)
  database:
    access-type: SQL
  notification:
    transport: kafka  # or 'http' for synchronous mode
    kafka:
      topic:
        link-updates: link-updates
        link-updates-dlt: link-updates.DLT
